model:
  name: "baseline_cnn"
  input_channels: 1
  num_classes: 2  # bonafide, spoof

data:
  root_dir: "./data/asvspoof2019"
  track: "LA"
  features: "logmel"
  sample_rate: 16000
  n_fft: 1024
  hop_length: 256
  n_mels: 64
  max_len_sec: 4 # Fixed duration for CNN input
  pad_mode: "wrap"

training:
  batck_size: 32
  epochs: 20
  learning_rate: 0.001
  weight_decay: 0.0001
  device: "cuda"  # or cpu
  output_dir: "./outputs/baseline_cnn"
  early_stopping_patience: 5
